### DISCUSSION TITLE
Lilian Vasconcelos

### DISCUSSION THREAD

**Discussion by liliancsv** [eerison/myprofile#731] [Resume]
### Resume structure

```yaml
    
    basic:
        firstName: Lilian
        lastName: Vasconcelos
        photoUrl: https://user-images.githubusercontent.com/17271315/226870708-6ba1777d-1af6-4643-89f3-fe8f7d11378f.jpg
        position: QA Testerin
    
    sectionOne:
        #[experience section]
        -   title: Berufliche Laufbahn
            icon: work
            children:
                -   company: Instituto Atlântico
                    position: QA Testerin
                    timePeriod: Nov 2020 – Nov 2021
                    description: |
                       - Das Projekt, das mir zugeteilt wurde, erbrachte Dienstleistungen für die Firma HP - Information Technology & Services. Testen des gesamten Anmelde-/Registrierungs-/Kontoerstellungsablaufs.
                       - Ich war dafür verantwortlich, die Qualität des Projekts sicherzustellen, Fehler festzustellen zur Korrektur zu öffnen, automatisierte Tests zu erstellen, zu prüfen, ob sie die Pipeline korrekt durchlaufen, zu prüfen, ob es notwendig ist, Funktionen für das Projekt zu erstellen, die Dokumentation zu aktualisieren und die zu unterstützen Entwicklungsteam, falls Zweifel bezüglich der Fehler oder Tests bestehen.
      
                -   company: Foton Informática
                    position: QA Testerin
                    timePeriod: Sep 2019 – Nov 2020
                    description: Zugeteilt in einer Bundesbank, arbeitete ich an Re-Testing, automatischem Test und auch manueller Test, der die Qualität des Systems dokumentiert und sicherstellt mit agilen Methoden und auch einem Finanzprojekt habe ich Neues kennengelernt Testtools von IBM.
    
                -   company: Adtalem Global Education
                    position: QA Testerin
                    timePeriod: Apr 2019 – Sep 2019
                    description: Ich war verantwortlich für die Qualitätssicherung des Studentenportals, außerdem erstellte ich ein Skript zur Automatisierung eines Prozesses im Finanzbereich. Mit manuellen Tests und automatisierten Tests.

                -   company: Techway
                    position: Testanalytikerin
                    timePeriod: Nov 2017 – Apr 2019
                    description: Techway ist ein Unternehmen für Beratung und Entwicklung von Technologielösungen. Mein Service wurde einem anderen Unternehmen zugewiesen, einem Unternehmen von Gesundheitsplänen - Hapvida. Dort war ich für das Testen des Systems, die Erfüllung der Anforderungen mit dem Kunden, die Abnahme des Systems und die Durchführung von Datenbankabfragen verantwortlich.

                -   company: Mob Telecom
                    position: Front End Entwicklerin
                    timePeriod: Mai 2016 - Nov 2017
                    description: Mob Telecom ist ein Unternehmen, dessen Hauptprodukte Hosting und Internetanbieter sind. Ich habe mit Front-End-Entwicklern zusammengearbeitet und das Konzept der Benutzererfahrung in Layouts verwendet.
        
    sectionTwo:
        #[skill section]
        -   title: ~
            icon: ~
            children:
                -   tag: Manueller Test
                -   tag: Automatisierter Test
                -   tag: Agiler Prozess
    
        #[contact section]
        -   title: ~
            icon: ~
            children:
                -   title: +49 0174 8708368
                    icon: phone
    
                -   title: lilian.ifce@gmail.com
                    icon: email
    
                -   title: https://www.linkedin.com/in/l-vasconcelos/
                    icon: linkedin
           
        #[education section]
        -   title: Ausbildung
            icon: education
            children:
                -   degree: Systemanalyse und -entwicklung
                    institution: Faculdade Fametro - an der Brasilien Universität
                    timePeriod: 2014 – 2016
    
                -   degree: Computertechniker
                    institution: IFCE - an der Brasilien Fachschule
                    timePeriod: 2009 – 2013
    
        #[language section]
        -   title: Fremdsprachen
            icon: language
            children:
                -   tag: ['Deutsch', 'Niveau B2']
                -   tag: ['English', 'gut in Wort und Schrift']
```
