### DISCUSSION TITLE
Moses Okpara

### DISCUSSION THREAD

**Discussion by 0xDamian** [eerison/myprofile#742] [Resume]
### Moses Resume

```yaml
basic:
    firstName: Moses
    lastName: Okpara
    photoUrl: https://media.licdn.com/dms/image/D4D03AQGQu1hUSIJtsQ/profile-displayphoto-shrink_800_800/0/1675199965604?e=1685577600&v=beta&t=z3_GnGKygNp5Li2yaoZb3EiExvhJPaamLuS_9AEI5-k
    position: Penetration Tester

sectionOne:
    #[about section]
    -   title: About
        icon: fileDescription
        children:
            -   content: |
                    B.Sc Cyber Security undergraduate with practical experience in various Cyber Security fields.
                    Particularly experienced in Web Application security and technical content writing. 

    #[experience section]
    -   title: Experiences
        icon: work
        children:
            -   company: Fezzant
                position: Penetration Tester & Technical Writer Intern
                timePeriod: October 2022 - Febuary 2023, U.K (Remote)
                description: |
                    **Penesting and Technical writing**

                    1. **Web Application Security**: Assisted in the assessment of web application security vulnerabilities and implemented remediation measures to improve overall security posture. Conducted regular security testing and monitoring to ensure the ongoing security of client cloud based web applications.
                    1. **Content Scripting**: Conducted research on various cyber security topics to inform and enhance the development of web content for viewer/customer consumption. Created and edited web content within the scope and guidelines of each project.
                website: https://www.fezzant.com/
                photoUrl: https://www.fezzant.com/static/media/new-fezzant-logo-m.90596ec5437d56cfc75561ff0b3fc66f.svg

            -   company: Cyblack
                position: Cyber Security Intern
                timePeriod: September 2022 - December 2022, U.K (Remote)
                locations: U.K, remote
                description: |
                    **Performed various Cyber Security tasks.**

                    1. As **Team lead**; Responsible for gathering individual reports, including writing and editing team reports for each task below.
                    1. Threat Intelligence.
                    1. Implementing **RBAC** in Azure Cloud VM.
                    1. Human Factor in Cyber Security Research.
                    1. GRC/Security Auditing.
                    1. Incident Response.
                    1. Penetration Testing.
                website: https://cyblack.org/
                photoUrl: https://cyblack.org/wp-content/uploads/2022/10/cropped-cyblack_logo-1.png

sectionTwo:
    #[skill section]
    -   title: ~
        icon: ~
        children:
            -   tag: Networking
            -   tag: Automation
            -   tag: Python
            -   tag: Web Security
            -   tag: Cloud Security
            -   tag: Azure
            -   tag: IAM
            -   tag: Teamwork
            -   tag: Problem-solving
            -   tag: Communication
            -   tag: Decision Making

    #[contact section]
    -   title: ~
        icon: ~
        children:
            -   title: +234 7016295610
                icon: phone

            -   title: damnsec@protonmail.com
                icon: email

            -   title: https://www.linkedin.com/in/moses-i-o-29a48122b/
                icon: linkedin

            -   title: https://github.com/0xDamian
                icon: github

    #[education section]
    -   title: Education
        icon: education
        children:
            -   degree: Bachelor of Science
                institution: Caleb University
                timePeriod: November 2021 - August 2025

    #[language section]
    -   title: Language
        icon: language
        children:
            -   tag: ['English', 'Native']
            -   tag: ['German', 'Independent User']

    #[certification section]
    -   title: Certifications
        icon: certification
        children:
            -   title: Certified Application Security Professional
                photoUrl: https://secops.group/wp-content/uploads/2023/01/cert-stamp-2.png
                timePeriod: since March 2023
                website: ~

            -   title: Cisco Cyber Security Essentials
                photoUrl: https://media.licdn.com/dms/image/D560BAQGRHOdaPHPKEQ/company-logo_100_100/0/1665765655002?e=1687996800&v=beta&t=B0YcD_EGFqLbG6HP1MSxpIGFhrN9w6igP_JLb1zyc4E
                timePeriod: since April 2022
                website: ~           
```
