### DISCUSSION TITLE
Rahul Gupta

### DISCUSSION THREAD

**Discussion by rghanks** [eerison/myprofile#749] [Resume]
### Resume structure

```yaml 
basic:
    firstName : Rahul 
    lastName : Gupta
    photoUrl: https://rghanks.github.io/portfolio/assets/img/IMG_20220825_202454_1.jpg
    position: Software Developer

sectionOne:
    #[about section]
    -   title: About
        icon: fileDescription
        children:
            -   content: |
                    Blockchain developer with 3 years of experience building decentralized applications and smart contracts
                    using Solidity, Ethereum, and other blockchain technologies. Proficient in developing web3.js applications
                    and integrating them with decentralized finance (DeFi) protocols. Proven ability to lead and mentor 
                    junior developers, collaborate with cross-functional teams, and deliver high-quality code on time.

    #[experience section]
    -   title: Experiences
        icon: work
        children:
            -   company: Nadcab Technology
                position: Blockchain Developer
                timePeriod: 2019 - current
                description: |
                    Responsible for designing and implementing decentralized applications that run on a blockchain network, 
                    ensuring that they are secure, scalable, and efficient.

                    1. Blockchain development (Ethereum, Hyperledger Fabric, Corda)
                    2. Smart contract development (Solidity)
                    3. Decentralized application development (DApp)
                    4. Cryptocurrency development
                    5. Blockchain architecture design
                    6. API development
                    7. Node.js and JavaScript
                    8. Web3.js and Truffle
                    9. Git and GitHub
                website: https://analog.exchange
                photoUrl: https://www.nadcab.com/public/uploads/logo.png

    #[certification section]
    # -   title: Certifications
    #     icon: certification
    #     children:
    #         -   title: Master of Arts
    #             photoUrl: https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Google__CompTIA_Badge.jpg
    #             timePeriod: March 2012 - December 2013
    #             website: ~

    #         -   title: Master of Arts
    #             photoUrl: https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Google__CompTIA_Badge.jpg
    #             timePeriod: March 2012 - December 2013
    #             website: ~

    #         -   title: Master of Arts
    #             photoUrl: https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Google__CompTIA_Badge.jpg
    #             timePeriod: March 2012 - December 2013
    #             website: ~

sectionTwo:
    #[skill section]
    -   title: ~
        icon: ~
        children:
            -   tag: HTML5
            -   tag: CSS3
            -   tag: JavaScript
            -   tag: Node.js
            -   tag: React.js
            -   tag: MongoDB

    #[contact section]
    -   title: ~
        icon: ~
        children:
            -   title: +91 1234567890
                icon: phone

            -   title: rghanks01@gmail.com
                icon: email

            -   title: https://www.linkedin.com/in/rghanks
                icon: linkedin

            -   title: https://github.com/rghanks
                icon: github

    #[education section]
    -   title: Education
        icon: education
        children:
            -   degree: B.Tech in Computer Science & Engineering
                institution: Abdul Kalam Technical University
                timePeriod: Aug 2019 - April 2022

            -   degree: Diploma in Computer Science & Engineering
                institution: Board of Technical University
                timePeriod: Aug 2015 - April 2018
    #[language section]
    -   title: Language
        icon: language
        children:
            -   tag: ['English', 'Intermediate']
            -   tag: ['Hindi', 'Intermediate']
```
