### DISCUSSION TITLE
Eduardo Carrillo

### DISCUSSION THREAD

**Discussion by ecarrillo01** [eerison/myprofile#767] [Resume]
### Resume structure

```yaml
      basic:
          firstName: Eduardo
          lastName: Carrillo
          position: Software Developer
      
      sectionOne:
          #[about section]
          -   title: About
              icon: fileDescription
              children:
                  -   content: |
                          **Lorem** *Ipsum* ~is~ _simply_ [dummy](https://www.google.com) text of the printing and typesetting industry. 
                          Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                          when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
                          It has survived not only five centuries, but also the leap into electronic typesetting, 
                          remaining essentially unchanged. It was popularised in the 1960s with the release of 
                          Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing 
                          software like Aldus PageMaker including versions of Lorem Ipsum.
      
          #[experience section]
          -   title: Experiences
              icon: work
              children:
                  -   title: JMD Mobile Solutions
                      position: React dev
                      timePeriod: since 2019
                          1. React app development using:Typescript, material ui, turf, geojson, function components,
and hooks for Mapbox Gl application.
                          2. In charge of the front end part of a project development.
                          3.  Do code reviews of other programmers.
                          4.  Design REST calls to streamline user interface performance.
                      website: https://example.com
                      photoUrl: https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-suite-everything-you-need-know-about-google-newest-0.png
      
                  -   company: Company B
                      position: Frontend Developer
                      timePeriod: January 2015 - December 2015
                      description: Fulfillment of extremely important tasks.
                      website: https://example.com
                      photoUrl: https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-suite-everything-you-need-know-about-google-newest-0.png
      
                  -   company: Company C
                      position: Trainee
                      timePeriod: March 2014 - December 2014
                      description: Making coffee and baking cookies.
                      website: ~
                      photoUrl: ~
      
          #[certification section]
          -   title: Certifications
              icon: certification
              children:
                  -   title: Master of Arts
                      photoUrl: https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Google__CompTIA_Badge.jpg
                      timePeriod: March 2012 - December 2013
                      website: ~
      
                  -   title: Master of Arts
                      photoUrl: https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Google__CompTIA_Badge.jpg
                      timePeriod: March 2012 - December 2013
                      website: ~
      
                  -   title: Master of Arts
                      photoUrl: https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Google__CompTIA_Badge.jpg
                      timePeriod: March 2012 - December 2013
                      website: ~
      
      sectionTwo:
          #[skill section]
          -   title: ~
              icon: ~
              children:
                  -   tag: HTML5
                  -   tag: CSS3
                  -   tag: JavaScript
                  -   tag: Node.js
      
          #[contact section]
          -   title: ~
              icon: ~
              children:
                  -   title: +49 123456789
                      icon: phone
      
                  -   title: email@gmail.com
                      icon: email
      
                  -   title: https://linkedin.com/eerison
                      icon: linkedin
      
                  -   title: https://github.com/eerison
                      icon: github
      
          #[education section]
          -   title: Education
              icon: education
              children:
                  -   degree: Master of Arts
                      institution: Harvard
                      timePeriod: March 2012 - December 2013
      
                  -   degree: Bachelor of Science
                      institution: Harvard
                      timePeriod: March 2009 - December 2011
          #[language section]
          -   title: Language
              icon: language
              children:
                  -   tag: ['English', 'Intermediate']
                  -   tag: ['Portuguese', 'Native']
      
          #[certification section]
          -   title: Certifications
              icon: certification
              children:
                  -   title: Sumo logic certified fundamentals
                      photoUrl: https://user-images.githubusercontent.com/6358755/226971473-a3064429-9567-4cb9-80f2-77b332125a0e.png
                      timePeriod: December 2019 - December 2020
                      website: ~
      
                  -   title: Zend Certified PHP Engineer 2017
                      photoUrl: https://user-images.githubusercontent.com/6358755/226969617-612c5fc9-1859-4708-9212-2cb36143fdfd.gif
                      timePeriod: since November 2017
                      website: ~            
```
