### DISCUSSION TITLE
My cool resume

### DISCUSSION THREAD

**Discussion by KingOfGerrit** [eerison/myprofile#772] [Resume]
### Resume structure

```yaml
      basic:
          firstName: Andrii
          lastName: Oliinyk
          photoUrl: https://media.licdn.com/dms/image/C5603AQHEFDmZq0t5EA/profile-displayphoto-shrink_400_400/0/1576841052839?e=1689206400&v=beta&t=QvSIAmJVErUTQDEb-27bB-47Ht4qHEcV-gjGrqWUFiQ
          position: C++ Senior Software Engineer
      
      sectionOne:
          #[about section]
          -   title: About
              icon: fileDescription
              children:
                  -   content: Hard-working, a responsible developer with a thirst for new knowledge, who is open to all possibilities and ready for all challenges. Organized and lead Scrum in a team with 8 members. Worked in SAFe, drive improvements on ART level (SAFe).
      
          #[experience section]
          -   title: Experiences
              icon: work
              children:
                  -   company: PoWa
                      position: Senior Software Engineer
                      timePeriod: since Sep 2022
                      description: Implemented the backend side of the iOS app. Create and support a daemon to sync data between the dealership's db and PoWa db. Use boost HTTP library to get data from REST API. Rewrite time-critical Python modules to C++.
                      website: ~
                      photoUrl: ~
      
                  -   company: Luxoft
                      position: Senior Software Engineer
                      timePeriod: Jan 2021 - Sep 2022
                      description: Implemented HMI (human-machine interface) for the automotive project. Support and fully refactor module "software update". Worked with C++14, C++17.
                      website: https://luxoft.com
                      photoUrl: ~
      
                  -   company: Developex
                      position: Software Engineer
                      timePeriod: Nov 2019 - Dec 2020
                      description: Participated in the development of a desktop application for Windows and macOS. Developed and support the "user data collection" module based on Mixpanel. Developed and support the "support user" module based on Zendesk. Worked with C++14, C++17, Qt, QML, CMake, and REST API.
                      website: https://developex.com
                      photoUrl: ~

                  -   company: GlobalLogic
                      position: Scrum Master + Software Engineer
                      timePeriod: Jan 2019 - Nov 2019
                      description: Developed a base platform for the automotive project (Low-level services and wrappers on the system). Organized and lead Scrum in a team with 8 members. Worked in SAFe, driving improvements on the ART level. Worked with C++14, C99, Docker, Python, Jenkins, setup CI, Linux, QNX, AUTOSAR Classic, AUTOSAR Adaptive, ISO-26262, and CMake.
                      website: https://globallogic.com
                      photoUrl: ~

                  -   company: GlobalLogic
                      position: Software Engineer
                      timePeriod: Sep 2018 - Dec 2018
                      description: Developed a base platform for the automotive project (Low-level services and wrappers on the system). Worked with C++14, C99, Docker, Python, Jenkins, setup CI, Linux, QNX, AUTOSAR Classic, AUTOSAR Adaptive, ISO-26262, and CMake.
                      website: https://globallogic.com
                      photoUrl: ~

                  -   company: Luxoft
                      position: Junior Software Engineer
                      timePeriod: Apr 2018 - Aug 2018
                      description: Worked with an Emergency call system for an automotive project. Worked with Qt, QML, C++11, Git, Linux, CMake.
                      website: https://luxoft.com
                      photoUrl: ~

                  -   company: Freelancer - Self employed
                      position: Embedded Software Developer
                      timePeriod: Aug 2016 - Apr 2018
                      description: Worked with Arduino framework to develop different commercial automation systems.
                      website: ~
                      photoUrl: ~
      
      sectionTwo:
          #[skill section]
          -   title: ~
              icon: ~
              children:
                  -   tag: Object-Oriented Programming (OOP)
                  -   tag: Agile Methodologies
                  -   tag: Scrum
                  -   tag: C++
                  -   tag: C++11
                  -   tag: C++14
                  -   tag: C++17
                  -   tag: Python
                  -   tag: Linux
                  -   tag: Qt
                  -   tag: Git
                  -   tag: C
                  -   tag: TensorFlow
                  -   tag: Automotive
                  -   tag: QML
      
          #[contact section]
          -   title: ~
              icon: ~
              children:
                  -   title: +1 (314)2620326
                      icon: phone
      
                  -   title: andrey.manuna@gmail.com
                      icon: email
      
                  -   title: https://www.linkedin.com/in/andrew-oliinyk/
                      icon: linkedin
      
                  -   title: https://github.com/KingOfGerrit
                      icon: github
      
          #[education section]
          -   title: Education
              icon: education
              children:
                  -   degree: Bachelor of Technology - Software Engineer
                      institution: Zhytomyr Polytechnic State University
                      timePeriod: 2021 - 2022
      
                  -   degree: Bachelor of Technology - Software Engineer
                      institution: National Aviation University
                      timePeriod: 2018 - 2021

                  -   degree: Junior Specialist - Software Engineer
                      institution: College of Engineering and Management
                      timePeriod: 2014 - 2018

          #[language section]
          -   title: Language
              icon: language
              children:
                  -   tag: ['English', 'Upper-Intermediate']
                  -   tag: ['Ukranian', 'Native']
       
```
