### DISCUSSION TITLE
Seth Emmanuel

### DISCUSSION THREAD

**Discussion by SethKhalif** [eerison/myprofile#774] [Resume]
### Resume structure
```yaml
      basic:
          firstName: Seth
          lastName: Emmanuel
          photoUrl: https://avatars.githubusercontent.com/u/6358755?v=4
          position: Junior Security Analyst
          
      
      sectionOne:
          #[about section]
          -   title: About
              icon: fileDescription
              children:
                  -   content: |
                                    As a Junior security Analyst, I bring a passion for cybersecurity and dedication to protecting organizations from emerging threats. 
                   
                                    While I may not hold a Bachelor's or Master's degree in a related field, I have taken extensive coursework in cybersecurity, networking, operating systems, and security concepts through self-study and hands-on experience. With little background in IT support and network administration, I have developed an eye for identifying vulnerabilities and approach to mitigating potential risks. 
                   
                                     My experience includes working with security tools such as SIEM, vulnerability scanners, as well as conducting investigations and producing detailed incident reports. As a lifelong learner, I am always seeking out new challenges and opportunities to expand my knowledge and skills. I am excited to join a team of like-minded professionals and to contribute my skills and enthusiasm to help organizations stay ahead of the evolving threat landscape.
      
          #[experience section]
          -   title: Experiences
              icon: work
              children:
                  -   company: Cyblack
                      position: Cyber Security Intern
                      timePeriod: Since April 2023, U.K (Remote)
                      description: |
                          **Performed various Cyber Security tasks**
                          1. As **Assistant Team Lead**; Responsible for gathering individual reports,            including writing and editing team reports for each task below.
                          1. Threat Intelligence.
                          1. Cloud Security.
                          1. Human Factor in Cyber Security Research.
                          1. GRC/Security Auditing.
                          1. Ethical Hacking.
                          1. Incident Response.
                      website: https://cyblack.org/
                      photoUrl: https://cyblack.org/wp-content/uploads/2023/04/cropped-cyblack_logo-e1680953130622.png
      
                  -   company: Deltech Cybercafe
                      position: IT Support
                      timePeriod: August 2022 - April 2023, Nigeria (Freelance)
                      website: ~
                      photoUrl: ~
                      description: |
                             **Desktop and IT Support**
                                             1. Was the Help Desk Support personnel.
                                             1. Troubleshooting both Desktops and Network.
      
                  -   company: Deram Cybarcafe
                      position: IT Support
                      timePeriod: January 2022 - Jun 2022, Nigeria (Full-time)
                      description: |
                             **Desktop and IT Support**
                                             1. Implementing Security Policies on who is allowed into the office and how to access the computers.
                                             1. Was in charge of safeguarding the network as the network administrator.
                                             1. Maintaining the computers and fixed minor hardware issues.
                      photoUrl: https://www.finelib.com/images/listings/25472_company_logo.JPG
                      website: ~
      
          #[certification section]
          -   title: Certifications
              icon: certification
              children:
                  -   title: Endpoint Security
                      photoUrl: https://images.credly.com/size/340x340/images/0ca5f542-fb5e-4a22-9b7a-c1a1ce4c3db7/EndpointSecurity.png
                      timePeriod: Since December 2022
                      website: ~
      
                  -   title: Networking Devices and Initial Configuration
                      photoUrl: https://images.credly.com/size/340x340/images/88316fe8-5651-4e61-a6be-5be1558f049e/image.png
                      timePeriod: Since October 2022
                      website: ~
      
                  -   title: Cybersecurity Fundamentals
                      photoUrl: https://images.credly.com/size/340x340/images/af8c6b4e-fc31-47c4-8dcb-eb7a2065dc5b/I2CS__1_.png
                      timePeriod: Since September 2022
                      website: ~
      
      sectionTwo:
          #[skill section]
          -   title: ~
              icon: ~
              children:
                  -   tag: SIEM
                  -   tag: Incident Response
                  -   tag: Threat Detection
                  -   tag: Vulnerability Management
                  -   tag: Security Awareness
                  -   tag: Critical Thinking
                  -   tag: Problem Solving
                  -   tag: Help Desk Support
                  -   tag: Implementing Security Policies
      
          #[contact section]
          -   title: ~
              icon: ~
              children:
                  -   title: +234 8147236923
                      icon: phone
      
                  -   title: sethemma10@yahoo.com
                      icon: email
      
                  -   title: https//:www.linkedin.com/in/seth-emmanuel
                      icon: linkedin
      
                  -   title: https://github.com/SethKhalif
                      icon: github
      
          #[education section]
          -   title: Education
              icon: education
              children:
                  -   degree: Certification
                      institution: Cisco Networking Academy
                      timePeriod: Since August 2022
      
          #[language section]
          -   title: Language
              icon: language
              children:
                  -   tag: ['English', 'Native']
                  -   tag: ['Spanish', 'Basic']
 ```
