### DISCUSSION TITLE
Isu Momodu Abdulrauf

### DISCUSSION THREAD

**Discussion by hackysterio** [eerison/myprofile#782] [Resume]
### Resume structure

```yaml
      basic:
          firstName: Abdulrauf
          lastName: Isu Momodu
          photoUrl: https://avatars.githubusercontent.com/u/6358755?v=4
          position: Cybersecurity Analyst
      
      sectionOne:
          #[about section]
          -   title: About
              icon: fileDescription
              children:
                  -   content: |
                          **Lorem** *Ipsum* ~is~ _simply_ [dummy](https://www.google.com) text of the printing and typesetting industry. 
                          B.Sc Chemistry graduate with a passion for Cybersecurity. I have developed practical skills in SSL/TLS implementation, API security, SIEM, and Open Source Intelligence. With a strong understanding of cybersecurity compliance, I can provide effective solutions aligned with industry standards. I am dedicated to educating others on best practices and staying up-to-date with the latest trends in the field. I have actively volunteered at Cybersecurity conferences, conducting hacking demonstrations to raise awareness. With a desire to make a meaningful contribution, I am ready to leverage my skills and knowledge to excel in the cybersecurity industry. 1500s, 
      
          #[experience section]
          -   title: Experiences
              icon: work
              children:
                  -   company: Company A
                      position: Developer
                      timePeriod: since January 2016
                      description: |
                          ***Programming and watching cute cat videos.**
      
                          1. item1
                          1. item2
                          1. item3
                      website: https://example.com
                      photoUrl: https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-suite-everything-you-need-know-about-google-newest-0.png
      
                  -   company: Company B
                      position: Frontend Developer
                      timePeriod: January 2015 - December 2015
                      description: Fulfillment of extremely important tasks.
                      website: https://example.com
                      photoUrl: https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-suite-everything-you-need-know-about-google-newest-0.png
      
                  -   company: Company C
                      position: Trainee
                      timePeriod: March 2014 - December 2014
                      description: Making coffee and baking cookies.
                      website: ~
                      photoUrl: ~
      
          #[certification section]
          -   title: Certifications
              icon: certification
              children:
                  -   title: Master of Arts
                      photoUrl: https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Google__CompTIA_Badge.jpg
                      timePeriod: March 2012 - December 2013
                      website: ~
      
                  -   title: Master of Arts
                      photoUrl: https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Google__CompTIA_Badge.jpg
                      timePeriod: March 2012 - December 2013
                      website: ~
      
                  -   title: Master of Arts
                      photoUrl: https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Google__CompTIA_Badge.jpg
                      timePeriod: March 2012 - December 2013
                      website: ~
      
      sectionTwo:
          #[skill section]
          -   title: ~
              icon: ~
              children:
                  -   tag: HTML5
                  -   tag: CSS3
                  -   tag: JavaScript
                  -   tag: Node.js
      
          #[contact section]
          -   title: ~
              icon: ~
              children:
                  -   title: +49 123456789
                      icon: phone
      
                  -   title: email@gmail.com
                      icon: email
      
                  -   title: https://linkedin.com/eerison
                      icon: linkedin
      
                  -   title: https://github.com/eerison
                      icon: github
      
          #[education section]
          -   title: Education
              icon: education
              children:
                  -   degree: Master of Arts
                      institution: Harvard
                      timePeriod: March 2012 - December 2013
      
                  -   degree: Bachelor of Science
                      institution: Harvard
                      timePeriod: March 2009 - December 2011
          #[language section]
          -   title: Language
              icon: language
              children:
                  -   tag: ['English', 'Intermediate']
                  -   tag: ['Portuguese', 'Native']
      
          #[certification section]
          -   title: Certifications
              icon: certification
              children:
                  -   title: Sumo logic certified fundamentals
                      photoUrl: https://user-images.githubusercontent.com/6358755/226971473-a3064429-9567-4cb9-80f2-77b332125a0e.png
                      timePeriod: December 2019 - December 2020
                      website: ~
      
                  -   title: Zend Certified PHP Engineer 2017
                      photoUrl: https://user-images.githubusercontent.com/6358755/226969617-612c5fc9-1859-4708-9212-2cb36143fdfd.gif
                      timePeriod: since November 2017
                      website: ~            
```
